WebApplication008/Controllers/MateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebApplication008.Models;
using WebApplication008.WCFServicioDatos;

namespace WebApplication008.Controllers
{
    public class MateriaController : Controller
    {
        // GET: Materia
        public ActionResult Index()
        {
            WCFServicioDatos.ServiceClient myCliente = new WCFServicioDatos.ServiceClient();
            List<MateriaModel> lstRecord = new List<MateriaModel>();
            var myListaMaterias = myCliente.ListarMaterias();

            foreach (var item in myListaMaterias)
            {
                MateriaModel materia = new MateriaModel();

                materia.Id_materia = item.id_materia;
                materia.Nombre = item.nombre.Trim();
                materia.Codigo = item.codigo.Trim();
                materia.Descripcion = item.descripcion.Trim();

                lstRecord.Add(materia);
            }

            if (Session["UserName"] != null)
            {
                return View(lstRecord.ToList());
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        // GET: Materia/Details/5
        public ActionResult Details(int id)
        {
            WCFServicioDatos.ServiceClient myCliente = new WCFServicioDatos.ServiceClient();
            var objMateria = myCliente.ListarMateriasPorId(id);

            var MyMateria = new MateriaModel();

            MyMateria.Id_materia = id;

            MyMateria.Nombre = objMateria[0].nombre.Trim();

            MyMateria.Codigo = objMateria[0].codigo.Trim();

            MyMateria.Descripcion = objMateria[0].descripcion.Trim();

            if (Session["UserName"] != null)
            {
                return View(MyMateria);
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        // GET: Materia/Create
        public ActionResult Create()
        {
            return View(new MateriaModel()); //Se actualiza a UserModel
        }

        // POST: Materia/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection, MateriaModel objMateria)
        {
            try
            {
                WCFServicioDatos.ServiceClient myCliente = new WCFServicioDatos.ServiceClient();

                try
                {
                    WCFServicioDatos.Materias TblMateria = new WCFServicioDatos.Materias();
                    //TblUsuario.Id = 0;
                    TblMateria.id_materia = objMateria.Id_materia;
                    TblMateria.nombre = objMateria.Nombre.Trim();
                    TblMateria.codigo = objMateria.Codigo.Trim();
                    TblMateria.descripcion = objMateria.Descripcion.Trim();

                    bool Resval = myCliente.CrearMateria(TblMateria);

                    if (Session["UserName"] != null)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Login");
                    }
                }
                catch
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Materia/Edit/5
        public ActionResult Edit(int id)
        {
            WCFServicioDatos.ServiceClient myCliente = new WCFServicioDatos.ServiceClient();
            var myMateria = myCliente.ListarMateriasPorId(id).ToList();

            try
            {
                if (ModelState.IsValid)
                {
                    var materia = new MateriaModel();

                    materia.Id_materia = myMateria[0].id_materia;
                    materia.Nombre = myMateria[0].nombre;
                    materia.Codigo = myMateria[0].codigo;
                    materia.Descripcion = myMateria[0].descripcion;

                    if (Session["UserName"] != null)
                    {
                        return View(materia);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Login");
                    }
                }
                else
                {
                    return View();
                }
            }
            catch (Exception)
            {
                return View();
            }
        }
    

        // POST: Materia/Edit/5
        [HttpPost]
        public ActionResult Edit(MateriaModel objMateria, FormCollection collection)
        {
            WCFServicioDatos.ServiceClient myCliente = new WCFServicioDatos.ServiceClient();
            bool resVal = false;
            try
            {
                if (ModelState.IsValid)
                {
                    WCFServicioDatos.Materias materias = new WCFServicioDatos.Materias();

                    materias.id_materia = objMateria.Id_materia;
                    materias.nombre = objMateria.Nombre;
                    materias.codigo = objMateria.Codigo;
                    materias.descripcion = objMateria.Descripcion;
                
                    resVal = myCliente.EditarMateria(materias); //actualiza objeto Materias
                    return RedirectToAction("Index");
                }
                else
                {
                    return View();
                }
            }
            catch(Exception)
            {
                return View();
            }
        }

        // GET: Materia/Delete/5
        public ActionResult Delete(int id)
        {
            WCFServicioDatos.ServiceClient myCliente = new WCFServicioDatos.ServiceClient();
            var myMateria = myCliente.ListarMateriasPorId(id);

            try
            {
                if (ModelState.IsValid)
                {
                    var materia = new MateriaModel();
                    materia.Id_materia = myMateria[0].id_materia;
                    materia.Nombre  = myMateria[0].nombre.Trim();
                    materia.Codigo = myMateria[0].codigo.Trim();
                    materia.Descripcion = myMateria[0].descripcion.Trim();

                    if (Session["UserName"] != null)
                    {
                        return View(materia);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Login");
                    }
                }
                else
                {
                    return View();
                }
            }
            catch (Exception)
            {
                return View();
            }
        }

        // POST: Materia/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                WCFServicioDatos.ServiceClient myCliente = new WCFServicioDatos.ServiceClient();
                bool Rev = myCliente.EliminarMateriaPorId(id);                
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication008/Views/Materia/Create.cshtml
@model WebApplication008.Models.MateriaModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear Materia</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MateriaModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-outline-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al Listado", "Index")
</div>

WebApplication008/Views/Materia/Delete.cshtml
@model WebApplication008.Models.MateriaModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Borrar</h2>

<h3>Esta seguro que desea borrar esto?</h3>
<div>
    <h4>Materia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" onclick="return confirm('Desea eliminar esta Materia?');" value="Borrar" class="btn btn-outline-success" /> |
            @Html.ActionLink("Regresar al listado", "Index")
        </div>
    }
</div>

WebApplication008/Views/Materia/Details.cshtml
@model WebApplication008.Models.MateriaModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles</h2>

<div>
    <h4>Materia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id_materia }) |
    @Html.ActionLink("Regresar al listado", "Index")
</p>

WebApplication008/Views/Materia/Edit.cshtml
@model WebApplication008.Models.MateriaModel

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Materia</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_materia)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-outline-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar al Listado", "Index")
</div>

WebApplication008/Views/Materia/Index.cshtml
@model IEnumerable<WebApplication008.Models.MateriaModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Materias</h2>

<p>
    @Html.ActionLink("Crear Nueva", "Create", "Materia", null, new { @class = "" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id_materia }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.Id_materia }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id_materia })
        </td>
    </tr>
}

</table>
<div>
    @Html.ActionLink("Regresar al menu", "Index", "Home")
</div>